### ISSUE TITLE
pageLoadTransactionName config not used

### ISSUE THREAD

**Issue by nicolasguilhem** [elastic/apm-agent-rum-js#1347]
I am using pageLoadTransactionName as the documentation says (https://www.elastic.co/guide/en/apm/agent/rum-js/current/custom-transaction-name.html) but transaction name doesn't change.

Seems that transaction name take config only if `tr.name === NAME_UNKNOWN` :
- at start of the transaction : https://github.com/elastic/apm-agent-rum-js/blob/main/packages/rum-core/src/performance-monitoring/transaction-service.js#L181
- or at end : https://github.com/elastic/apm-agent-rum-js/blob/main/packages/rum-core/src/performance-monitoring/transaction-service.js#L281

How to change "page-load" transaction name ? Transaction name is initialised with "undefined". How could it be initialised to `NAME_UNKNOWN` ?

**Comment by devcorpio** [comment]
Hi @nicolasguilhem,

Thanks for reaching out!

- Could you share the RUM initialization snippet? 
- What version of the agent are you using? 

Thanks,
Alberto

**Comment by devcorpio** [comment]
hmm, the config looks good.

I assume you are initializing the agent from the application module or component as the [docs](https://www.elastic.co/guide/en/apm/agent/rum-js/current/angular-integration.html#_instrumenting_your_angular_application) describe.

Questions:

- Is the name of the transaction also `undefined` if you remove the `pageLoadTransactionName` option? 
- How are you checking that value? Is Kibana showing you the "undefined"? 
- What version of the Elastic Stack are you using?
- Could you share the output from the snippet below? - it will log a transaction when ending. (redact sensitive information if needed)
```
    apmService.observe("transaction:end", (tr: any) => {
      console.log("tr", tr)
  })
```
- Could you share the payload of the event request?  

<img width="487" alt="Screenshot 2023-03-09 at 16 48 19" src="https://user-images.githubusercontent.com/15065076/224077781-4332a547-05b8-4f27-a4ed-8dcd925542cd.png">

In Chromium browsers an event payload is sent compressed, you will need to follow the steps [here](https://www.elastic.co/guide/en/apm/agent/rum-js/master/troubleshooting.html#disable-events-payload-compression) to see the payload decompressed. An alternative is to use a non-chromium browser such as Firefox, or Safari. Sharing a HAR file - making sure the events are not compressed - would be an alternative if you want.


Please, redact all the information that you deem sensitive.


Cheers,
Alberto

**Comment by nicolasguilhem** [comment]
Thanks @devcorpio for helping ;)

First of all, agent is initialized at Angular initialization using APP_INITIALIZER in initializer factory :

```typescript
@NgModule({
  declarations: [AppComponent],
  imports: [importedModules],
  providers: [
    {
      provide: APP_INITIALIZER,
      useFactory: initializer,
      deps: [
        KeycloakService,
        ApmService,
        EnvironmentService,
        ElectronService,
        LoadingService,
        BackendStatusService,
      ],
      multi: true,
    },
    {
      provide: ErrorHandler,
      useClass: ApmErrorHandler,
    },
  ],
  bootstrap: [AppComponent],
})
export class AppModule {}
```

Next, transaction name of page-load is not "undefined" but is calculated with URL present in browser. I finnaly found how transaction name is set at beginning with "Unknown". It is set in constructor of SpanBase [here](https://github.com/elastic/apm-agent-rum-js/blob/main/packages/rum-core/src/performance-monitoring/span-base.js#L41) (inherited by Transaction class).

If I remove `pageLoadTransactionName`, it doesn't change, transaction name of page-load is the one calculated as default (URL).

Value is checked in Kibana wich is in version 7.17.8.

I can't use the snippet you provided as the APM Rum Angular does not expose an "observe" method with this signature. The method is used by AP Rum Angular for route-change transactions (see [here](https://github.com/elastic/apm-agent-rum-js/blob/main/packages/rum-angular/src/apm.service.ts#L61)) ...
But i'll try next week with `apmService.apm.observe ....`, i'll check payload too next week.

Thanks a lot @devcorpio

**Comment by devcorpio** [comment]
Hi @nicolasguilhem,

> But i'll try next week with apmService.apm.observe ...., i'll check payload too next week.

```apmService.init({```

**Comment by devcorpio** [comment]
Hi @nicolasguilhem,

> But i'll try next week with apmService.apm.observe ...., i'll check payload too next week.

```apmService.init({```

init returns an instance of ```apm```, then you could use:

const apm = apmService.init(...

**Comment by nicolasguilhem** [comment]
I've done tests and result with the code above is :

```typescript
            const apm = apmService.init({
            serverUrl: environmentService.environment.apm.serverUrl,
            serviceName: environmentService.environment.apm.serviceName,
            distributedTracing:
              environmentService.environment.apm.distributedTracing,
            distributedTracingOrigins: [
              environmentService.environment.apm.distributedTracingOrigins,
            ],
          });
          const wantedTransactionName = window.location.pathname;
          console.log('wantedTransactionName', wantedTransactionName);
          apm.config({ pageLoadTransactionName: wantedTransactionName });
          apm.observe('transaction:end', (tr) => console.log('tr', tr));

```
(also tried with pageLoadTransactionName directly in init and the result is the same).

console logs are : (can't past printscreen ...)

```
wantedTransactionName /mes-contextes
tr Transaction {name: '/mes-contextes?idContexte=2', type: 'page-load', options: {…}, id: 'e700f060d847a6b9', traceId: '870cd2362c15d7bdc96ce396335626e1', …}
blocked: false
breakdownTimings: []
captureTimings: true
context: {page: {…}, response: {…}}
ended: true
experience: {tbt: 3271, cls: 0, longtask: {…}}
id: "e700f060d847a6b9"
marks: {agent: {…}, navigationTiming: {…}}
name: "/mes-contextes"
onEnd: ƒ ()
length: 0
name: ""
prototype: {constructor: ƒ}
arguments: (...)
caller: (...)
options: 
      canReuse: true
      managed: true
      pageLoadSampled: false
      pageLoadSpanId: ""
      pageLoadTraceId: ""
      pageLoadTransactionName: "/mes-contextes"
      reuseThreshold: undefined
      transactionSampleRate: 1
```
